---
title: "Louis_D Intro to low level R"
author: "Louis DROGO"
format: html
editor: visual
---

```{r}
#| message: false
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)

here::i_am("intro-low-level-R.Rproj")
```


## Types and classes

### Types

```{r}
typeof(1.5) # double
typeof("test") # character
typeof(TRUE) # logical
typeof(1L) # integer
typeof(1) # double
typeof(typeof) # closure : it's a function essentially
typeof(list()) # list
```

Every numbers are considered as double unless you specify it's an integer.


### Classes

```{r}
data(iris)
typeof(iris) # list
class(iris) # data frame

class(1) # numeric
class(1L) # integer
```
## Vector

Many things in R are vectors (and most of the other things are lists).
A vector is a collection of values of the same type (possibly a single value).

```{r}
w <- 15.25
length(w)  # all vectors have a length
w[1]
```

The c-function can be seen as a creation function or, more accurately, as a vector concatenation function.
```{r}
y <- c(1,-2,45,1.5,-1e-10)
y
typeof(y)
y[2]
length(y)
```

